In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Computer.use_jedi = False
import numpy as np
import pandas as pd
import requests

In [12]:
high_info = pd.read_csv('./data/고등학교 정보.csv')
high_info

,시도교육청,지역교육청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,학교특성,분교여부,설립유형,...,우편번호,학교도로명 우편번호,학교도로명 주소,학교도로명 상세주소,위도,경도,전화번호,팩스번호,홈페이지 주소,남녀공학 구분
0,서울특별시교육청,서울특별시교육청,서울특별시 송파구,S010000370,가락고등학교,4,공립,일반고등학교,N,단설,...,138170.0,5678,서울특별시 송파구 송이로 42,"(송파동,가락고등학교)",37.501637,127.116943,02-416-4658,02-421-9669,http://garak.sen.hs.kr,남녀공학
1,서울특별시교육청,서울특별시교육청,서울특별시 강동구,S010000371,강동고등학교,4,사립,일반고등학교,N,단설,...,134837.0,5279,서울특별시 강동구 구천면로 572,(상일동),37.549890,127.160702,02-427-0231,02-441-3494,http://kangdong.sen.hs.kr,남녀공학
2,서울특별시교육청,서울특별시교육청,서울특별시 양천구,S010000372,강서고등학교,4,사립,일반고등학교,N,단설,...,158814.0,7958,서울특별시 양천구 목동중앙남로 27,", 강서고등학교 (목동)",37.536777,126.866330,02-2642-0725,02-2651-3046,http://gangseo.sen.hs.kr,남
3,서울특별시교육청,서울특별시교육청,서울특별시 강남구,S010000373,개포고등학교,4,공립,일반고등학교,N,단설,...,135240.0,6324,서울특별시 강남구 개포로 402,"(개포동, 개포고등학교)",37.484959,127.059405,02-576-3333,02-571-6560,http://gaepo.sen.hs.kr,남녀공학
4,서울특별시교육청,서울특별시교육청,서울특별시 광진구,S010000374,건국대학교사범대학부속고등학교,4,사립,일반고등학교,N,부속,...,143701.0,5029,서울특별시 광진구 능동로 120,", 건국대학교사범대학부속고등학교 (화양동)",37.540060,127.080340,070-7012-3500,02-456-0646,http://konkuk.sen.hs.kr,남녀공학
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,서울특별시교육청,서울특별시교육청,서울특별시 서대문구,S010005591,가재울고등학교,4,공립,일반고등학교,N,단설,...,120811.0,3709,서울특별시 서대문구 수색로 100-35,(북가좌동),37.574297,126.909499,02-6351-0500,02-307-6605,http://gajaeul.sen.hs.kr,남녀공학
314,서울특별시교육청,서울특별시교육청,서울특별시 은평구,S010005616,하나고등학교,4,사립,자율고등학교,N,단설,...,122200.0,3305,서울특별시 은평구 연서로 535,", 하나고등학교 (진관동)",37.641637,126.936930,02-6913-1111,02-6913-1785,http://www.hana.hs.kr,남녀공학
315,서울특별시교육청,서울특별시교육청,서울특별시 성동구,S010006381,금호고등학교,4,공립,일반고등학교,N,단설,...,NaN,4727,서울특별시 성동구 금호로 118,(금호동1가),37.553250,127.023620,02-2022-0800,02-2022-0840,http://geumho.sen.hs.kr,남녀공학
316,서울특별시교육청,서울특별시교육청,서울특별시 성동구,S010006382,도선고등학교,4,공립,일반고등학교,N,단설,...,NaN,4701,서울특별시 성동구 마장로 156,(하왕십리동),37.567131,127.026809,02-2292-8175,02-2292-7556,http://dosun.sen.hs.kr,남녀공학
317,서울특별시교육청,서울특별시교육청,서울특별시 송파구,S010006558,덕수고등학교(일반고),4,공립,일반고등학교,N,단설,...,NaN,5846,서울특별시 송파구 위례북로 10,"(거여동, 덕수고등학교)",37.485367,127.146854,02-6952-2801,02-449-9069,https://duksoowr.sen.hs.kr,남녀공학

In [13]:
high_info.columns

Index(['시도교육청', '지역교육청', '지역', '정보공시 학교코드', '학교명', '학교급코드', '설립구분', '학교특성',
       '분교여부', '설립유형', '주야구분', '개교기념일', '설립일', '법정동코드', '주소내역', '상세주소내역',
       '우편번호', '학교도로명 우편번호', '학교도로명 주소', '학교도로명 상세주소', '위도', '경도', '전화번호',
       '팩스번호', '홈페이지 주소', '남녀공학 구분'],
      dtype='object')

In [14]:
high_info.drop(columns=['시도교육청', '지역교육청','학교급코드', '지역', '정보공시 학교코드','설립구분', '학교특성',
       '분교여부', '설립유형', '주야구분', '개교기념일', '설립일', '법정동코드', '주소내역', '상세주소내역', '우편번호', '학교도로명 우편번호',
        '전화번호', '팩스번호', '홈페이지 주소', '남녀공학 구분'], inplace=True)
high_info

,학교명,학교도로명 주소,학교도로명 상세주소,위도,경도
0,가락고등학교,서울특별시 송파구 송이로 42,"(송파동,가락고등학교)",37.501637,127.116943
1,강동고등학교,서울특별시 강동구 구천면로 572,(상일동),37.549890,127.160702
2,강서고등학교,서울특별시 양천구 목동중앙남로 27,", 강서고등학교 (목동)",37.536777,126.866330
3,개포고등학교,서울특별시 강남구 개포로 402,"(개포동, 개포고등학교)",37.484959,127.059405
4,건국대학교사범대학부속고등학교,서울특별시 광진구 능동로 120,", 건국대학교사범대학부속고등학교 (화양동)",37.540060,127.080340
...,...,...,...,...,...
313,가재울고등학교,서울특별시 서대문구 수색로 100-35,(북가좌동),37.574297,126.909499
314,하나고등학교,서울특별시 은평구 연서로 535,", 하나고등학교 (진관동)",37.641637,126.936930
315,금호고등학교,서울특별시 성동구 금호로 118,(금호동1가),37.553250,127.023620
316,도선고등학교,서울특별시 성동구 마장로 156,(하왕십리동),37.567131,127.026809
317,덕수고등학교(일반고),서울특별시 송파구 위례북로 10,"(거여동, 덕수고등학교)",37.485367,127.146854

In [15]:
# 카카오맵 API Key
kakao_api_key = '146c824df784569973cb17777ddd3301'

high_info['행정동'] = None
high_info['시군구'] = None
# 카카오맵 API를 호출하여 주소별 위도, 경도 및 행정동명을 얻습니다.
for index, row in high_info.iterrows():
    latitude = row['위도']
    longitude = row['경도']
    
    url = f'https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x={longitude}&y={latitude}'
    headers = {
        'Authorization': f'KakaoAK {kakao_api_key}'
    }
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        data = response.json()
        if data.get('documents'):
            administrative_district1 = data['documents'][1]['region_3depth_name']
            administrative_district2 = data['documents'][1]['region_2depth_name']
            
            high_info.at[index, '행정동'] = administrative_district1
            high_info.at[index, '시군구'] = administrative_district2
            

# 결과를 출력합니다.
high_info

,학교명,학교도로명 주소,학교도로명 상세주소,위도,경도,행정동,시군구
0,가락고등학교,서울특별시 송파구 송이로 42,"(송파동,가락고등학교)",37.501637,127.116943,송파2동,송파구
1,강동고등학교,서울특별시 강동구 구천면로 572,(상일동),37.549890,127.160702,상일1동,강동구
2,강서고등학교,서울특별시 양천구 목동중앙남로 27,", 강서고등학교 (목동)",37.536777,126.866330,목4동,양천구
3,개포고등학교,서울특별시 강남구 개포로 402,"(개포동, 개포고등학교)",37.484959,127.059405,개포2동,강남구
4,건국대학교사범대학부속고등학교,서울특별시 광진구 능동로 120,", 건국대학교사범대학부속고등학교 (화양동)",37.540060,127.080340,화양동,광진구
...,...,...,...,...,...,...,...
313,가재울고등학교,서울특별시 서대문구 수색로 100-35,(북가좌동),37.574297,126.909499,북가좌1동,서대문구
314,하나고등학교,서울특별시 은평구 연서로 535,", 하나고등학교 (진관동)",37.641637,126.936930,진관동,은평구
315,금호고등학교,서울특별시 성동구 금호로 118,(금호동1가),37.553250,127.023620,금호1가동,성동구
316,도선고등학교,서울특별시 성동구 마장로 156,(하왕십리동),37.567131,127.026809,왕십리도선동,성동구
317,덕수고등학교(일반고),서울특별시 송파구 위례북로 10,"(거여동, 덕수고등학교)",37.485367,127.146854,위례동,송파구

In [16]:
high_info.drop(columns=['학교도로명 주소', '학교도로명 상세주소', '위도', '경도'], inplace=True)
high_info

                 학교명     행정동   시군구
0             가락고등학교    송파2동   송파구
1             강동고등학교    상일1동   강동구
2             강서고등학교     목4동   양천구
3             개포고등학교    개포2동   강남구
4    건국대학교사범대학부속고등학교     화양동   광진구
..               ...     ...   ...
313          가재울고등학교   북가좌1동  서대문구
314           하나고등학교     진관동   은평구
315           금호고등학교   금호1가동   성동구
316           도선고등학교  왕십리도선동   성동구
317      덕수고등학교(일반고)     위례동   송파구

[318 rows x 3 columns]

In [17]:
high_info.to_csv('./data/행정동시군구학교명.csv')
high_info

                 학교명     행정동   시군구
0             가락고등학교    송파2동   송파구
1             강동고등학교    상일1동   강동구
2             강서고등학교     목4동   양천구
3             개포고등학교    개포2동   강남구
4    건국대학교사범대학부속고등학교     화양동   광진구
..               ...     ...   ...
313          가재울고등학교   북가좌1동  서대문구
314           하나고등학교     진관동   은평구
315           금호고등학교   금호1가동   성동구
316           도선고등학교  왕십리도선동   성동구
317      덕수고등학교(일반고)     위례동   송파구

[318 rows x 3 columns]

In [18]:
# '강북구, '도봉구', '노원구' , '중랑구', '동대문구' 선택
selected_districts = ['강북구', '도봉구', '노원구', '성북구', '중랑구', '동대문구']
filtered_df = high_info[high_info['시군구'].isin(selected_districts)]
filtered_df

                 학교명   행정동   시군구
7             경동고등학교   삼선동   성북구
14            경희고등학교  이문1동  동대문구
15          경희여자고등학교   회기동  동대문구
16            계성고등학교  길음1동   성북구
17   고려대학교사범대학부속고등학교  정릉3동   성북구
..               ...   ...   ...
291           원묵고등학교   묵1동   중랑구
297          삼각산고등학교  삼각산동   강북구
305         해성여자고등학교  전농2동  동대문구
306           솔샘고등학교   삼양동   강북구
309           휘봉고등학교  휘경2동  동대문구

[76 rows x 3 columns]

In [19]:
grouped = filtered_df.groupby(['시군구', '행정동']).size().reset_index(name='학교수')
grouped

     시군구      행정동  학교수
0    강북구      미아동    1
1    강북구     삼각산동    1
2    강북구      삼양동    1
3    강북구      송중동    1
4    강북구      송천동    2
5    강북구     수유1동    1
6    노원구     공릉2동    2
7    노원구    상계10동    1
8    노원구     상계1동    1
9    노원구   상계6.7동    1
10   노원구     상계8동    1
11   노원구     상계9동    2
12   노원구     월계1동    1
13   노원구     월계2동    4
14   노원구     중계1동    1
15   노원구   중계2.3동    3
16   노원구     중계4동    2
17   노원구     중계본동    3
18   노원구     하계1동    3
19   도봉구     도봉1동    1
20   도봉구     도봉2동    1
21   도봉구     방학1동    1
22   도봉구     쌍문1동    1
23   도봉구     쌍문4동    3
24   도봉구      창1동    1
25   도봉구      창4동    2
26  동대문구      용신동    1
27  동대문구     이문1동    1
28  동대문구     장안2동    1
29  동대문구     전농2동    2
30  동대문구      제기동    1
31  동대문구     청량리동    1
32  동대문구      회기동    1
33  동대문구     휘경2동    3
34   성북구     길음1동    1
35   성북구     돈암1동    1
36   성북구      동선동    1
37   성북구      삼선동    2
38   성북구      석관동    1
39   성북구      성북동    2
40   성북구      안암동    1
41   성북구     월곡1동    1
42   성북구     정릉3동    1
43   성북구     정릉4동    2
44   중랑구     망우3동    1
45   중랑구     망우본동    4
46   중랑구  면목제3.8동    1
47   중랑구      묵1동    2
48   중랑구     상봉1동    1
49   중랑구     중화1동    1

In [21]:
width = pd.read_csv('./data/h동북부면적.csv')
width

     시군구     행정동    면적
0   동대문구     회기동  0.76
1   동대문구    휘경1동  0.63
2   동대문구    휘경2동  1.05
3   동대문구    청량리동  1.20
4   동대문구     용신동  1.61
..   ...     ...   ...
91   노원구   상계10동  0.80
92   노원구  상계3.4동  5.05
93   노원구  상계6.7동  1.11
94   노원구  중계2.3동  0.90
95   노원구    공릉1동  1.41

[96 rows x 3 columns]

In [30]:
merged_df = pd.merge(grouped, width, on=['시군구', '행정동'], how='inner')
merged_df

     시군구     행정동  학교수    면적
0    강북구     미아동    1  0.93
1    강북구    삼각산동    1  0.62
2    강북구     삼양동    1  0.91
3    강북구     송중동    1  1.01
4    강북구     송천동    2  0.90
5    강북구    수유1동    1  1.67
6    노원구    공릉2동    2  6.82
7    노원구   상계10동    1  0.80
8    노원구    상계1동    1  5.62
9    노원구  상계6.7동    1  1.11
10   노원구    상계8동    1  0.67
11   노원구    상계9동    2  0.81
12   노원구    월계1동    1  1.16
13   노원구    월계2동    4  1.94
14   노원구    중계1동    1  0.63
15   노원구  중계2.3동    3  0.90
16   노원구    중계4동    2  1.70
17   노원구    중계본동    3  1.97
18   노원구    하계1동    3  1.55
19   도봉구    도봉1동    1  8.72
20   도봉구    도봉2동    1  0.83
21   도봉구    방학1동    1  0.69
22   도봉구    쌍문1동    1  1.24
23   도봉구    쌍문4동    3  0.52
24   도봉구     창1동    1  0.88
25   도봉구     창4동    2  0.95
26  동대문구     용신동    1  1.61
27  동대문구    이문1동    1  1.04
28  동대문구    장안2동    1  1.09
29  동대문구    전농2동    2  0.86
30  동대문구     제기동    1  1.18
31  동대문구    청량리동    1  1.20
32  동대문구     회기동    1  0.76
33  동대문구    휘경2동    3  1.05
34   성북구    길음1동    1  0.79
35   성북구    돈암1동    1  0.49
36   성북구     동선동    1  0.73
37   성북구     삼선동    2  0.92
38   성북구     석관동    1  1.73
39   성북구     성북동    2  2.86
40   성북구     안암동    1  1.33
41   성북구    월곡1동    1  0.81
42   성북구    정릉3동    1  3.71
43   성북구    정릉4동    2  3.13
44   중랑구    망우3동    1  0.92
45   중랑구    망우본동    4  3.03
46   중랑구     묵1동    2  1.20
47   중랑구    상봉1동    1  0.88
48   중랑구    중화1동    1  0.64

In [31]:
merged_df['면적(㎢)당 학교 수'] = ( merged_df['학교수'] / merged_df['면적']).round(2)
merged_df

     시군구     행정동  학교수    면적  면적(㎢)당 학교 수
0    강북구     미아동    1  0.93         1.08
1    강북구    삼각산동    1  0.62         1.61
2    강북구     삼양동    1  0.91         1.10
3    강북구     송중동    1  1.01         0.99
4    강북구     송천동    2  0.90         2.22
5    강북구    수유1동    1  1.67         0.60
6    노원구    공릉2동    2  6.82         0.29
7    노원구   상계10동    1  0.80         1.25
8    노원구    상계1동    1  5.62         0.18
9    노원구  상계6.7동    1  1.11         0.90
10   노원구    상계8동    1  0.67         1.49
11   노원구    상계9동    2  0.81         2.47
12   노원구    월계1동    1  1.16         0.86
13   노원구    월계2동    4  1.94         2.06
14   노원구    중계1동    1  0.63         1.59
15   노원구  중계2.3동    3  0.90         3.33
16   노원구    중계4동    2  1.70         1.18
17   노원구    중계본동    3  1.97         1.52
18   노원구    하계1동    3  1.55         1.94
19   도봉구    도봉1동    1  8.72         0.11
20   도봉구    도봉2동    1  0.83         1.20
21   도봉구    방학1동    1  0.69         1.45
22   도봉구    쌍문1동    1  1.24         0.81
23   도봉구    쌍문4동    3  0.52         5.77
24   도봉구     창1동    1  0.88         1.14
25   도봉구     창4동    2  0.95         2.11
26  동대문구     용신동    1  1.61         0.62
27  동대문구    이문1동    1  1.04         0.96
28  동대문구    장안2동    1  1.09         0.92
29  동대문구    전농2동    2  0.86         2.33
30  동대문구     제기동    1  1.18         0.85
31  동대문구    청량리동    1  1.20         0.83
32  동대문구     회기동    1  0.76         1.32
33  동대문구    휘경2동    3  1.05         2.86
34   성북구    길음1동    1  0.79         1.27
35   성북구    돈암1동    1  0.49         2.04
36   성북구     동선동    1  0.73         1.37
37   성북구     삼선동    2  0.92         2.17
38   성북구     석관동    1  1.73         0.58
39   성북구     성북동    2  2.86         0.70
40   성북구     안암동    1  1.33         0.75
41   성북구    월곡1동    1  0.81         1.23
42   성북구    정릉3동    1  3.71         0.27
43   성북구    정릉4동    2  3.13         0.64
44   중랑구    망우3동    1  0.92         1.09
45   중랑구    망우본동    4  3.03         1.32
46   중랑구     묵1동    2  1.20         1.67
47   중랑구    상봉1동    1  0.88         1.14
48   중랑구    중화1동    1  0.64         1.56

In [32]:
merged_df.drop(columns=['학교수', '면적'], inplace=True)
merged_df

     시군구     행정동  면적(㎢)당 학교 수
0    강북구     미아동         1.08
1    강북구    삼각산동         1.61
2    강북구     삼양동         1.10
3    강북구     송중동         0.99
4    강북구     송천동         2.22
5    강북구    수유1동         0.60
6    노원구    공릉2동         0.29
7    노원구   상계10동         1.25
8    노원구    상계1동         0.18
9    노원구  상계6.7동         0.90
10   노원구    상계8동         1.49
11   노원구    상계9동         2.47
12   노원구    월계1동         0.86
13   노원구    월계2동         2.06
14   노원구    중계1동         1.59
15   노원구  중계2.3동         3.33
16   노원구    중계4동         1.18
17   노원구    중계본동         1.52
18   노원구    하계1동         1.94
19   도봉구    도봉1동         0.11
20   도봉구    도봉2동         1.20
21   도봉구    방학1동         1.45
22   도봉구    쌍문1동         0.81
23   도봉구    쌍문4동         5.77
24   도봉구     창1동         1.14
25   도봉구     창4동         2.11
26  동대문구     용신동         0.62
27  동대문구    이문1동         0.96
28  동대문구    장안2동         0.92
29  동대문구    전농2동         2.33
30  동대문구     제기동         0.85
31  동대문구    청량리동         0.83
32  동대문구     회기동         1.32
33  동대문구    휘경2동         2.86
34   성북구    길음1동         1.27
35   성북구    돈암1동         2.04
36   성북구     동선동         1.37
37   성북구     삼선동         2.17
38   성북구     석관동         0.58
39   성북구     성북동         0.70
40   성북구     안암동         0.75
41   성북구    월곡1동         1.23
42   성북구    정릉3동         0.27
43   성북구    정릉4동         0.64
44   중랑구    망우3동         1.09
45   중랑구    망우본동         1.32
46   중랑구     묵1동         1.67
47   중랑구    상봉1동         1.14
48   중랑구    중화1동         1.56

In [33]:
merged_df[merged_df['행정동'] == '중계본동']

    시군구   행정동  면적(㎢)당 학교 수
17  노원구  중계본동         1.52

In [34]:
merged_df.to_csv('./data/h동북부학교수.csv')
merged_df

     시군구     행정동  면적(㎢)당 학교 수
0    강북구     미아동         1.08
1    강북구    삼각산동         1.61
2    강북구     삼양동         1.10
3    강북구     송중동         0.99
4    강북구     송천동         2.22
5    강북구    수유1동         0.60
6    노원구    공릉2동         0.29
7    노원구   상계10동         1.25
8    노원구    상계1동         0.18
9    노원구  상계6.7동         0.90
10   노원구    상계8동         1.49
11   노원구    상계9동         2.47
12   노원구    월계1동         0.86
13   노원구    월계2동         2.06
14   노원구    중계1동         1.59
15   노원구  중계2.3동         3.33
16   노원구    중계4동         1.18
17   노원구    중계본동         1.52
18   노원구    하계1동         1.94
19   도봉구    도봉1동         0.11
20   도봉구    도봉2동         1.20
21   도봉구    방학1동         1.45
22   도봉구    쌍문1동         0.81
23   도봉구    쌍문4동         5.77
24   도봉구     창1동         1.14
25   도봉구     창4동         2.11
26  동대문구     용신동         0.62
27  동대문구    이문1동         0.96
28  동대문구    장안2동         0.92
29  동대문구    전농2동         2.33
30  동대문구     제기동         0.85
31  동대문구    청량리동         0.83
32  동대문구     회기동         1.32
33  동대문구    휘경2동         2.86
34   성북구    길음1동         1.27
35   성북구    돈암1동         2.04
36   성북구     동선동         1.37
37   성북구     삼선동         2.17
38   성북구     석관동         0.58
39   성북구     성북동         0.70
40   성북구     안암동         0.75
41   성북구    월곡1동         1.23
42   성북구    정릉3동         0.27
43   성북구    정릉4동         0.64
44   중랑구    망우3동         1.09
45   중랑구    망우본동         1.32
46   중랑구     묵1동         1.67
47   중랑구    상봉1동         1.14
48   중랑구    중화1동         1.56