In [1]:
import warnings
warnings.filterwarnings(action='ignore')
%config Computer.use_jedi = False
import numpy as np
import pandas as pd

In [2]:
house = pd.read_csv('./data/동북부집값.csv')
house = house.drop(columns=['Unnamed: 0'], axis=1)
# house['면적(㎢)당금액'] = house['면적(㎡)당금액'] * 0.001
# house.drop(columns=['면적(㎡)당금액'], inplace=True)
house

     시군구   법정동  면적(㎡)당금액
0    강북구   미아동     990.0
1    강북구    번동     922.0
2    강북구   수유동     965.0
3    강북구   우이동     755.0
4    노원구   공릉동    1016.0
5    노원구   상계동    1115.0
6    노원구   월계동    1213.0
7    노원구   중계동    1169.0
8    노원구   하계동    1222.0
9    도봉구   도봉동     784.0
10   도봉구   방학동     791.0
11   도봉구   쌍문동     786.0
12   도봉구    창동    1075.0
13  동대문구  답십리동    1164.0
14  동대문구   신설동    1228.0
15  동대문구   용두동    1278.0
16  동대문구   이문동    1132.0
17  동대문구   장안동     942.0
18  동대문구   전농동    1438.0
19  동대문구   제기동     949.0
20  동대문구  청량리동    1185.0
21  동대문구   회기동     989.0
22  동대문구   휘경동    1232.0
23   성북구   길음동    1321.0
24   성북구  상월곡동     922.0
25   성북구   석관동    1259.0
26   성북구   성북동     562.0
27   성북구  시가지동     994.0
28   성북구   장위동    1216.0
29   성북구   정릉동    1132.0
30   성북구   종암동    1172.0
31   성북구  하월곡동    1020.0
32   중랑구   망우동     785.0
33   중랑구   면목동     974.0
34   중랑구    묵동     914.0
35   중랑구   상봉동    1147.0
36   중랑구   신내동     936.0
37   중랑구   중화동     790.0

In [3]:
school = pd.read_csv('./data/동북부학교수.csv')
school = school.drop(columns=['Unnamed: 0'], axis=1)
school

     시군구   법정동  면적(㎢)당 학교 수
0    강북구   미아동     2.230483
1    강북구   수유동     0.406504
2    노원구   공릉동     1.226994
3    노원구   상계동     1.562500
4    노원구   월계동     3.676471
5    노원구   중계동     5.263158
6    노원구   하계동     3.658537
7    도봉구   도봉동     1.801802
8    도봉구   방학동     0.709220
9    도봉구   쌍문동     2.702703
10   도봉구    창동     1.388889
11  동대문구   신설동     4.545455
12  동대문구   이문동     1.098901
13  동대문구   장안동     0.680272
14  동대문구   전농동     2.127660
15  동대문구   제기동     1.388889
16  동대문구  청량리동     1.612903
17  동대문구   회기동     3.571429
18  동대문구   휘경동     3.488372
19   성북구   길음동     1.123596
20   성북구   석관동     1.470588
21   성북구   성북동     1.923077
22   성북구  시가지동     2.092050
23   성북구   정릉동     1.666667
24   성북구  하월곡동     0.952381
25   중랑구   망우동     4.310345
26   중랑구   면목동     0.409836
27   중랑구    묵동     2.222222
28   중랑구   상봉동     1.204819
29   중랑구   중화동     1.190476

In [4]:
merge = pd.merge(house, school, on=['시군구', '법정동'], how='left')
merge

     시군구   법정동  면적(㎡)당금액  면적(㎢)당 학교 수
0    강북구   미아동     990.0     2.230483
1    강북구    번동     922.0          NaN
2    강북구   수유동     965.0     0.406504
3    강북구   우이동     755.0          NaN
4    노원구   공릉동    1016.0     1.226994
5    노원구   상계동    1115.0     1.562500
6    노원구   월계동    1213.0     3.676471
7    노원구   중계동    1169.0     5.263158
8    노원구   하계동    1222.0     3.658537
9    도봉구   도봉동     784.0     1.801802
10   도봉구   방학동     791.0     0.709220
11   도봉구   쌍문동     786.0     2.702703
12   도봉구    창동    1075.0     1.388889
13  동대문구  답십리동    1164.0          NaN
14  동대문구   신설동    1228.0     4.545455
15  동대문구   용두동    1278.0          NaN
16  동대문구   이문동    1132.0     1.098901
17  동대문구   장안동     942.0     0.680272
18  동대문구   전농동    1438.0     2.127660
19  동대문구   제기동     949.0     1.388889
20  동대문구  청량리동    1185.0     1.612903
21  동대문구   회기동     989.0     3.571429
22  동대문구   휘경동    1232.0     3.488372
23   성북구   길음동    1321.0     1.123596
24   성북구  상월곡동     922.0          NaN
25   성북구   석관동    1259.0     1.470588
26   성북구   성북동     562.0     1.923077
27   성북구  시가지동     994.0     2.092050
28   성북구   장위동    1216.0          NaN
29   성북구   정릉동    1132.0     1.666667
30   성북구   종암동    1172.0          NaN
31   성북구  하월곡동    1020.0     0.952381
32   중랑구   망우동     785.0     4.310345
33   중랑구   면목동     974.0     0.409836
34   중랑구    묵동     914.0     2.222222
35   중랑구   상봉동    1147.0     1.204819
36   중랑구   신내동     936.0          NaN
37   중랑구   중화동     790.0     1.190476

In [6]:
academy = pd.read_csv('./data/동북부학원수.csv')
academy = academy.drop(columns=['Unnamed: 0'], axis=1)
academy

     시군구   법정동  면적(㎢)당 학원 수
0    강북구   미아동    24.907063
1    강북구    번동    10.891089
2    강북구   수유동    15.040650
3    강북구   우이동     3.846154
4    노원구   공릉동    15.337423
5    노원구   상계동    26.041667
6    노원구   월계동    13.235294
7    노원구   중계동   113.450292
8    노원구   하계동    20.731707
9    도봉구   도봉동     4.504505
10   도봉구   방학동    21.985816
11   도봉구   쌍문동    27.027027
12   도봉구    창동    25.000000
13  동대문구  답십리동    15.686275
14  동대문구   신설동     4.545455
15  동대문구   용두동    15.789474
16  동대문구   이문동    23.076923
17  동대문구   장안동    35.374150
18  동대문구   전농동    28.723404
19  동대문구   제기동    13.888889
20  동대문구  청량리동     4.838710
21  동대문구   회기동     7.142857
22  동대문구   휘경동    13.953488
23   성북구   길음동    56.179775
24   성북구  상월곡동    10.000000
25   성북구   석관동    17.647059
26   성북구  시가지동    40.167364
27   성북구   장위동    12.408759
28   성북구   정릉동    14.444444
29   성북구   종암동    26.666667
30   성북구  하월곡동    23.809524
31   중랑구   망우동    14.655172
32   중랑구   면목동    11.065574
33   중랑구    묵동    22.222222
34   중랑구   상봉동    13.253012
35   중랑구   신내동    32.727273
36   중랑구   중화동     9.523810

In [7]:
merge = pd.merge(merge, academy, on=['시군구', '법정동'], how='left')
merge

     시군구   법정동  면적(㎡)당금액  면적(㎢)당 학교 수  면적(㎢)당 학원 수
0    강북구   미아동     990.0     2.230483    24.907063
1    강북구    번동     922.0          NaN    10.891089
2    강북구   수유동     965.0     0.406504    15.040650
3    강북구   우이동     755.0          NaN     3.846154
4    노원구   공릉동    1016.0     1.226994    15.337423
5    노원구   상계동    1115.0     1.562500    26.041667
6    노원구   월계동    1213.0     3.676471    13.235294
7    노원구   중계동    1169.0     5.263158   113.450292
8    노원구   하계동    1222.0     3.658537    20.731707
9    도봉구   도봉동     784.0     1.801802     4.504505
10   도봉구   방학동     791.0     0.709220    21.985816
11   도봉구   쌍문동     786.0     2.702703    27.027027
12   도봉구    창동    1075.0     1.388889    25.000000
13  동대문구  답십리동    1164.0          NaN    15.686275
14  동대문구   신설동    1228.0     4.545455     4.545455
15  동대문구   용두동    1278.0          NaN    15.789474
16  동대문구   이문동    1132.0     1.098901    23.076923
17  동대문구   장안동     942.0     0.680272    35.374150
18  동대문구   전농동    1438.0     2.127660    28.723404
19  동대문구   제기동     949.0     1.388889    13.888889
20  동대문구  청량리동    1185.0     1.612903     4.838710
21  동대문구   회기동     989.0     3.571429     7.142857
22  동대문구   휘경동    1232.0     3.488372    13.953488
23   성북구   길음동    1321.0     1.123596    56.179775
24   성북구  상월곡동     922.0          NaN    10.000000
25   성북구   석관동    1259.0     1.470588    17.647059
26   성북구   성북동     562.0     1.923077          NaN
27   성북구  시가지동     994.0     2.092050    40.167364
28   성북구   장위동    1216.0          NaN    12.408759
29   성북구   정릉동    1132.0     1.666667    14.444444
30   성북구   종암동    1172.0          NaN    26.666667
31   성북구  하월곡동    1020.0     0.952381    23.809524
32   중랑구   망우동     785.0     4.310345    14.655172
33   중랑구   면목동     974.0     0.409836    11.065574
34   중랑구    묵동     914.0     2.222222    22.222222
35   중랑구   상봉동    1147.0     1.204819    13.253012
36   중랑구   신내동     936.0          NaN    32.727273
37   중랑구   중화동     790.0     1.190476     9.523810

In [8]:
subway = pd.read_csv('./data/동북부지하철수.csv')
subway = subway.drop(columns=['Unnamed: 0'], axis=1)
subway

     시군구   법정동  면적(㎢)당 역 수
0   동대문구   신설동    0.009091
1   동대문구   용두동    0.002632
2   동대문구   제기동    0.000000
3   동대문구   전농동    0.002128
4   동대문구  답십리동    0.000000
5   동대문구   장안동    0.000000
6   동대문구  청량리동    0.000000
7   동대문구   회기동    0.000000
8   동대문구   휘경동    0.001163
9   동대문구   이문동    0.002198
10   중랑구   면목동    0.001230
11   중랑구   상봉동    0.003614
12   중랑구   중화동    0.002381
13   중랑구    묵동    0.001111
14   중랑구   망우동    0.001724
15   중랑구   신내동    0.001818
16   성북구   성북동    0.000000
17   성북구  시가지동    0.002510
18   성북구   정릉동    0.001111
19   성북구   길음동    0.001124
20   성북구   종암동    0.001333
21   성북구  하월곡동    0.000952
22   성북구  상월곡동    0.005000
23   성북구   장위동    0.000730
24   성북구   석관동    0.002941
25   강북구   미아동    0.001859
26   강북구    번동    0.000990
27   강북구   수유동    0.000813
28   강북구   우이동    0.005769
29   도봉구   쌍문동    0.000676
30   도봉구   방학동    0.000709
31   도봉구    창동    0.001389
32   도봉구   도봉동    0.002703
33   노원구   월계동    0.001471
34   노원구   공릉동    0.002454
35   노원구   하계동    0.001220
36   노원구   상계동    0.001563
37   노원구   중계동    0.000585

In [9]:
merge = pd.merge(merge, subway, on=['시군구', '법정동'], how='left')
merge

     시군구   법정동  면적(㎡)당금액  면적(㎢)당 학교 수  면적(㎢)당 학원 수  면적(㎢)당 역 수
0    강북구   미아동     990.0     2.230483    24.907063    0.001859
1    강북구    번동     922.0          NaN    10.891089    0.000990
2    강북구   수유동     965.0     0.406504    15.040650    0.000813
3    강북구   우이동     755.0          NaN     3.846154    0.005769
4    노원구   공릉동    1016.0     1.226994    15.337423    0.002454
5    노원구   상계동    1115.0     1.562500    26.041667    0.001563
6    노원구   월계동    1213.0     3.676471    13.235294    0.001471
7    노원구   중계동    1169.0     5.263158   113.450292    0.000585
8    노원구   하계동    1222.0     3.658537    20.731707    0.001220
9    도봉구   도봉동     784.0     1.801802     4.504505    0.002703
10   도봉구   방학동     791.0     0.709220    21.985816    0.000709
11   도봉구   쌍문동     786.0     2.702703    27.027027    0.000676
12   도봉구    창동    1075.0     1.388889    25.000000    0.001389
13  동대문구  답십리동    1164.0          NaN    15.686275    0.000000
14  동대문구   신설동    1228.0     4.545455     4.545455    0.009091
15  동대문구   용두동    1278.0          NaN    15.789474    0.002632
16  동대문구   이문동    1132.0     1.098901    23.076923    0.002198
17  동대문구   장안동     942.0     0.680272    35.374150    0.000000
18  동대문구   전농동    1438.0     2.127660    28.723404    0.002128
19  동대문구   제기동     949.0     1.388889    13.888889    0.000000
20  동대문구  청량리동    1185.0     1.612903     4.838710    0.000000
21  동대문구   회기동     989.0     3.571429     7.142857    0.000000
22  동대문구   휘경동    1232.0     3.488372    13.953488    0.001163
23   성북구   길음동    1321.0     1.123596    56.179775    0.001124
24   성북구  상월곡동     922.0          NaN    10.000000    0.005000
25   성북구   석관동    1259.0     1.470588    17.647059    0.002941
26   성북구   성북동     562.0     1.923077          NaN    0.000000
27   성북구  시가지동     994.0     2.092050    40.167364    0.002510
28   성북구   장위동    1216.0          NaN    12.408759    0.000730
29   성북구   정릉동    1132.0     1.666667    14.444444    0.001111
30   성북구   종암동    1172.0          NaN    26.666667    0.001333
31   성북구  하월곡동    1020.0     0.952381    23.809524    0.000952
32   중랑구   망우동     785.0     4.310345    14.655172    0.001724
33   중랑구   면목동     974.0     0.409836    11.065574    0.001230
34   중랑구    묵동     914.0     2.222222    22.222222    0.001111
35   중랑구   상봉동    1147.0     1.204819    13.253012    0.003614
36   중랑구   신내동     936.0          NaN    32.727273    0.001818
37   중랑구   중화동     790.0     1.190476     9.523810    0.002381

In [12]:
# '면적(㎢)당 금액' 칼럼을 '면적(㎡)당금액'을 맨 뒤로 이동
merge = merge[[col for col in merge if col != '면적(㎡)당금액'] + ['면적(㎡)당금액']]

# 변경된 데이터프레임을 출력하거나 저장할 수 있습니다.
merge

     시군구     법정동  면적(㎢)당 학교 수  면적(㎢)당 학원 수  면적(㎢)당 역 수  면적(㎡)당금액
0    강북구     미아동     1.372998    15.331808    1.144165     990.0
1    강북구      번동          NaN     4.059041    0.369004     922.0
2    강북구     수유동     0.160256     5.929487    0.320513     965.0
3    강북구     우이동          NaN     0.194553    0.291829     755.0
4    노원구     공릉동     0.243013     3.037667    0.486027    1016.0
5    노원구     상계동     0.382653     6.377551    0.382653    1115.0
6    노원구     월계동     1.170960     4.215457    0.468384    1213.0
7    노원구     중계동     1.730769    37.307692    0.192308    1169.0
8    노원구     하계동     1.456311     8.252427    0.485437    1222.0
9    도봉구     도봉동     0.209424     0.523560    0.314136     784.0
10   도봉구     방학동     0.246914     7.654321    0.246914     791.0
11   도봉구     쌍문동     1.428571    14.285714    0.357143     786.0
12   도봉구      창동     0.705882    12.705882    0.705882    1075.0
13  동대문구    답십리동          NaN     9.638554    0.000000    1164.0
14  동대문구     신설동          NaN          NaN         NaN    1228.0
15  동대문구     용두동          NaN     7.453416    1.242236    1278.0
16  동대문구     이문동     0.578035    12.138728    1.156069    1132.0
17  동대문구     장안동     0.427350    22.222222    0.000000     942.0
18  동대문구     전농동     0.975610    13.170732    0.975610    1438.0
19  동대문구     제기동     0.847458     8.474576    0.000000     949.0
20  동대문구    청량리동     0.833333     2.500000    0.000000    1185.0
21  동대문구     회기동     1.315789     2.631579    0.000000     989.0
22  동대문구     휘경동     1.785714     7.142857    0.595238    1232.0
23   성북구     길음동     0.729927    36.496350    0.729927    1321.0
24   성북구     돈암동     1.030928    23.711340    0.000000     973.0
25   성북구   동선동1가          NaN          NaN         NaN    1054.0
26   성북구   동선동4가          NaN          NaN         NaN     850.0
27   성북구  동소문동4가          NaN          NaN         NaN     928.0
28   성북구  동소문동5가          NaN          NaN         NaN    1400.0
29   성북구  동소문동7가          NaN          NaN         NaN    1083.0
30   성북구   보문동2가          NaN          NaN         NaN     617.0
31   성북구   보문동3가          NaN          NaN         NaN    1242.0
32   성북구   보문동4가          NaN          NaN         NaN     854.0
33   성북구   보문동6가          NaN          NaN         NaN    1599.0
34   성북구   삼선동2가          NaN          NaN         NaN    1034.0
35   성북구   삼선동3가          NaN          NaN         NaN    1105.0
36   성북구   삼선동4가          NaN     1.086957    0.000000    1034.0
37   성북구   삼선동5가          NaN          NaN         NaN     868.0
38   성북구    상월곡동          NaN     1.470588    0.735294     922.0
39   성북구     석관동     0.578035     6.936416    1.156069    1259.0
40   성북구     성북동     0.699301          NaN    0.000000     562.0
41   성북구   성북동1가          NaN          NaN         NaN    1375.0
42   성북구   안암동1가          NaN          NaN         NaN    1310.0
43   성북구   안암동3가          NaN          NaN         NaN     660.0
44   성북구   안암동4가          NaN          NaN         NaN     316.0
45   성북구   안암동5가          NaN          NaN         NaN     514.0
46   성북구     장위동          NaN     8.415842    0.495050    1216.0
47   성북구     정릉동     0.355030     3.076923    0.236686    1132.0
48   성북구     종암동          NaN    13.698630    0.684932    1172.0
49   성북구    하월곡동     1.234568    30.864198    1.234568    1020.0
50   중랑구     망우동     1.265823     4.303797    0.506329     785.0
51   중랑구     면목동     0.166389     4.492512    0.499168     974.0
52   중랑구      묵동     1.069519    10.695187    0.534759     914.0
53   중랑구     상봉동     0.653595     7.189542    1.960784    1147.0
54   중랑구     신내동          NaN    10.315186    0.573066     936.0
55   중랑구     중화동     0.606061     4.848485    1.212121     790.0

In [10]:
# '지하철 역 개수' 컬럼에서 NaN 값을 0으로 채웁니다.
merge['면적(㎢)당 역 수'].fillna(0, inplace=True)
merge['면적(㎢)당 학교 수'].fillna(0, inplace=True)
merge['면적(㎢)당 학원 수'].fillna(0, inplace=True)
merge

     시군구   법정동  면적(㎡)당금액  면적(㎢)당 학교 수  면적(㎢)당 학원 수  면적(㎢)당 역 수
0    강북구   미아동     990.0     2.230483    24.907063    0.001859
1    강북구    번동     922.0     0.000000    10.891089    0.000990
2    강북구   수유동     965.0     0.406504    15.040650    0.000813
3    강북구   우이동     755.0     0.000000     3.846154    0.005769
4    노원구   공릉동    1016.0     1.226994    15.337423    0.002454
5    노원구   상계동    1115.0     1.562500    26.041667    0.001563
6    노원구   월계동    1213.0     3.676471    13.235294    0.001471
7    노원구   중계동    1169.0     5.263158   113.450292    0.000585
8    노원구   하계동    1222.0     3.658537    20.731707    0.001220
9    도봉구   도봉동     784.0     1.801802     4.504505    0.002703
10   도봉구   방학동     791.0     0.709220    21.985816    0.000709
11   도봉구   쌍문동     786.0     2.702703    27.027027    0.000676
12   도봉구    창동    1075.0     1.388889    25.000000    0.001389
13  동대문구  답십리동    1164.0     0.000000    15.686275    0.000000
14  동대문구   신설동    1228.0     4.545455     4.545455    0.009091
15  동대문구   용두동    1278.0     0.000000    15.789474    0.002632
16  동대문구   이문동    1132.0     1.098901    23.076923    0.002198
17  동대문구   장안동     942.0     0.680272    35.374150    0.000000
18  동대문구   전농동    1438.0     2.127660    28.723404    0.002128
19  동대문구   제기동     949.0     1.388889    13.888889    0.000000
20  동대문구  청량리동    1185.0     1.612903     4.838710    0.000000
21  동대문구   회기동     989.0     3.571429     7.142857    0.000000
22  동대문구   휘경동    1232.0     3.488372    13.953488    0.001163
23   성북구   길음동    1321.0     1.123596    56.179775    0.001124
24   성북구  상월곡동     922.0     0.000000    10.000000    0.005000
25   성북구   석관동    1259.0     1.470588    17.647059    0.002941
26   성북구   성북동     562.0     1.923077     0.000000    0.000000
27   성북구  시가지동     994.0     2.092050    40.167364    0.002510
28   성북구   장위동    1216.0     0.000000    12.408759    0.000730
29   성북구   정릉동    1132.0     1.666667    14.444444    0.001111
30   성북구   종암동    1172.0     0.000000    26.666667    0.001333
31   성북구  하월곡동    1020.0     0.952381    23.809524    0.000952
32   중랑구   망우동     785.0     4.310345    14.655172    0.001724
33   중랑구   면목동     974.0     0.409836    11.065574    0.001230
34   중랑구    묵동     914.0     2.222222    22.222222    0.001111
35   중랑구   상봉동    1147.0     1.204819    13.253012    0.003614
36   중랑구   신내동     936.0     0.000000    32.727273    0.001818
37   중랑구   중화동     790.0     1.190476     9.523810    0.002381

### 상관관계 계산

In [47]:
# '시군구'와 '법정동'으로 그룹화하여 '면적(㎢)당 역 수' 및 '면적(㎡)당금액'의 평균 계산
grouped_data = merge.groupby(['시군구', '법정동'])[['면적(㎢)당 역 수', '면적(㎡)당금액']].mean()
correlation = grouped_data.corr()
correlation.loc['면적(㎢)당 역 수', '면적(㎡)당금액']

0.0768388617296292

In [48]:
# '시군구'와 '법정동'으로 그룹화하여 '면적(㎢)당 역 수' 및 '면적(㎡)당금액'의 평균 계산
grouped_data = merge.groupby(['시군구', '법정동'])[['면적(㎢)당 학교 수', '면적(㎡)당금액']].mean()
correlation = grouped_data.corr()
correlation.loc['면적(㎢)당 학교 수', '면적(㎡)당금액']

0.12256382016265525

In [49]:
# '시군구'와 '법정동'으로 그룹화하여 '면적(㎢)당 역 수' 및 '면적(㎡)당금액'의 평균 계산
grouped_data = merge.groupby(['시군구', '법정동'])[['면적(㎢)당 학원 수', '면적(㎡)당금액']].mean()
correlation = grouped_data.corr()
correlation.loc['면적(㎢)당 학원 수', '면적(㎡)당금액']

0.2664136776270923

In [12]:
import warnings
warnings.filterwarnings(action='ignore')
%config Completer.use_jedi = False
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from sklearn.preprocessing import StandardScaler # 스케일링을 위한 import

WARNING:tensorflow:From C:\anaconda3\envs\py37\lib\site-packages\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

In [13]:
data = merge
data

     시군구   법정동  면적(㎡)당금액  면적(㎢)당 학교 수  면적(㎢)당 학원 수  면적(㎢)당 역 수
0    강북구   미아동     990.0     2.230483    24.907063    0.001859
1    강북구    번동     922.0     0.000000    10.891089    0.000990
2    강북구   수유동     965.0     0.406504    15.040650    0.000813
3    강북구   우이동     755.0     0.000000     3.846154    0.005769
4    노원구   공릉동    1016.0     1.226994    15.337423    0.002454
5    노원구   상계동    1115.0     1.562500    26.041667    0.001563
6    노원구   월계동    1213.0     3.676471    13.235294    0.001471
7    노원구   중계동    1169.0     5.263158   113.450292    0.000585
8    노원구   하계동    1222.0     3.658537    20.731707    0.001220
9    도봉구   도봉동     784.0     1.801802     4.504505    0.002703
10   도봉구   방학동     791.0     0.709220    21.985816    0.000709
11   도봉구   쌍문동     786.0     2.702703    27.027027    0.000676
12   도봉구    창동    1075.0     1.388889    25.000000    0.001389
13  동대문구  답십리동    1164.0     0.000000    15.686275    0.000000
14  동대문구   신설동    1228.0     4.545455     4.545455    0.009091
15  동대문구   용두동    1278.0     0.000000    15.789474    0.002632
16  동대문구   이문동    1132.0     1.098901    23.076923    0.002198
17  동대문구   장안동     942.0     0.680272    35.374150    0.000000
18  동대문구   전농동    1438.0     2.127660    28.723404    0.002128
19  동대문구   제기동     949.0     1.388889    13.888889    0.000000
20  동대문구  청량리동    1185.0     1.612903     4.838710    0.000000
21  동대문구   회기동     989.0     3.571429     7.142857    0.000000
22  동대문구   휘경동    1232.0     3.488372    13.953488    0.001163
23   성북구   길음동    1321.0     1.123596    56.179775    0.001124
24   성북구  상월곡동     922.0     0.000000    10.000000    0.005000
25   성북구   석관동    1259.0     1.470588    17.647059    0.002941
26   성북구   성북동     562.0     1.923077     0.000000    0.000000
27   성북구  시가지동     994.0     2.092050    40.167364    0.002510
28   성북구   장위동    1216.0     0.000000    12.408759    0.000730
29   성북구   정릉동    1132.0     1.666667    14.444444    0.001111
30   성북구   종암동    1172.0     0.000000    26.666667    0.001333
31   성북구  하월곡동    1020.0     0.952381    23.809524    0.000952
32   중랑구   망우동     785.0     4.310345    14.655172    0.001724
33   중랑구   면목동     974.0     0.409836    11.065574    0.001230
34   중랑구    묵동     914.0     2.222222    22.222222    0.001111
35   중랑구   상봉동    1147.0     1.204819    13.253012    0.003614
36   중랑구   신내동     936.0     0.000000    32.727273    0.001818
37   중랑구   중화동     790.0     1.190476     9.523810    0.002381

In [14]:
# 법정동을 원-핫 인코딩
one_hot_encoded = pd.get_dummies(merge, columns=['법정동'])
one_hot_encoded

,시군구,면적(㎡)당금액,면적(㎢)당 학교 수,면적(㎢)당 학원 수,면적(㎢)당 역 수,법정동_공릉동,법정동_길음동,법정동_답십리동,법정동_도봉동,법정동_망우동,...,법정동_제기동,법정동_종암동,법정동_중계동,법정동_중화동,법정동_창동,법정동_청량리동,법정동_하계동,법정동_하월곡동,법정동_회기동,법정동_휘경동
0,강북구,990.0,2.230483,24.907063,0.001859,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,강북구,922.0,0.000000,10.891089,0.000990,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,강북구,965.0,0.406504,15.040650,0.000813,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,강북구,755.0,0.000000,3.846154,0.005769,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,노원구,1016.0,1.226994,15.337423,0.002454,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,노원구,1115.0,1.562500,26.041667,0.001563,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,노원구,1213.0,3.676471,13.235294,0.001471,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,노원구,1169.0,5.263158,113.450292,0.000585,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8,노원구,1222.0,3.658537,20.731707,0.001220,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9,도봉구,784.0,1.801802,4.504505,0.002703,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,도봉구,791.0,0.709220,21.985816,0.000709,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,도봉구,786.0,2.702703,27.027027,0.000676,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,도봉구,1075.0,1.388889,25.000000,0.001389,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13,동대문구,1164.0,0.000000,15.686275,0.000000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
14,동대문구,1228.0,4.545455,4.545455,0.009091,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,동대문구,1278.0,0.000000,15.789474,0.002632,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,동대문구,1132.0,1.098901,23.076923,0.002198,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,동대문구,942.0,0.680272,35.374150,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,동대문구,1438.0,2.127660,28.723404,0.002128,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,동대문구,949.0,1.388889,13.888889,0.000000,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
20,동대문구,1185.0,1.612903,4.838710,0.000000,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
21,동대문구,989.0,3.571429,7.142857,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,동대문구,1232.0,3.488372,13.953488,0.001163,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
23,성북구,1321.0,1.123596,56.179775,0.001124,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,성북구,922.0,0.000000,10.000000,0.005000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,성북구,1259.0,1.470588,17.647059,0.002941,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,성북구,562.0,1.923077,0.000000,0.000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,성북구,994.0,2.092050,40.167364,0.002510,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,성북구,1216.0,0.000000,12.408759,0.000730,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,성북구,1132.0,1.666667,14.444444,0.001111,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,성북구,1172.0,0.000000,26.666667,0.001333,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
31,성북구,1020.0,0.952381,23.809524,0.000952,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32,중랑구,785.0,4.310345,14.655172,0.001724,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
33,중랑구,974.0,0.409836,11.065574,0.001230,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,중랑구,914.0,2.222222,22.222222,0.001111,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,중랑구,1147.0,1.204819,13.253012,0.003614,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,중랑구,936.0,0.000000,32.727273,0.001818,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,중랑구,790.0,1.190476,9.523810,0.002381,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [51]:
# 데이터프레임을 넘파이 배열로 변환
numpy_array = one_hot_encoded.to_numpy()
numpy_array

array([['강북구', 990.0, 2.2304832713754648, ..., 0, 0, 0],
       ['강북구', 922.0, 0.0, ..., 0, 0, 0],
       ['강북구', 965.0, 0.4065040650406504, ..., 0, 0, 0],
       ...,
       ['중랑구', 1147.0, 1.2048192771084338, ..., 0, 0, 0],
       ['중랑구', 936.0, 0.0, ..., 0, 0, 0],
       ['중랑구', 790.0, 1.1904761904761905, ..., 0, 0, 0]], dtype=object)

In [69]:
# 넘파이 배열에서 변화 요인(피쳐) 데이터(학원수, 역수)로 사용할 데이터를 뽑아낸다. 
xData = numpy_array[:, 2:5]
print(type(xData))
xData

<class 'numpy.ndarray'>

array([[2.2304832713754648, 24.907063197026023, 0.0018587360594795],
       [0.0, 10.891089108910892, 0.0009900990099009],
       [0.4065040650406504, 15.040650406504064, 0.0008130081300813],
       [0.0, 3.846153846153846, 0.0057692307692307],
       [1.2269938650306749, 15.337423312883436, 0.0024539877300613],
       [1.5625, 26.041666666666668, 0.0015625],
       [3.676470588235294, 13.235294117647058, 0.0014705882352941],
       [5.2631578947368425, 113.45029239766082, 0.0005847953216374],
       [3.658536585365854, 20.731707317073173, 0.0012195121951219],
       [1.8018018018018016, 4.504504504504504, 0.0027027027027027],
       [0.7092198581560284, 21.98581560283688, 0.000709219858156],
       [2.702702702702702, 27.027027027027028, 0.0006756756756756],
       [1.3888888888888888, 25.0, 0.0013888888888888],
       [0.0, 15.68627450980392, 0.0],
       [4.545454545454546, 4.545454545454546, 0.009090909090909],
       [0.0, 15.789473684210526, 0.0026315789473684],
       [1.0989010989010988, 23.07692307692308, 0.0021978021978021],
       [0.6802721088435374, 35.374149659863946, 0.0],
       [2.127659574468085, 28.72340425531915, 0.002127659574468],
       [1.3888888888888888, 13.88888888888889, 0.0],
       [1.6129032258064515, 4.838709677419355, 0.0],
       [3.571428571428571, 7.142857142857142, 0.0],
       [3.488372093023256, 13.953488372093023, 0.0011627906976744],
       [1.1235955056179776, 56.17977528089887, 0.0011235955056179],
       [0.0, 10.0, 0.005],
       [1.4705882352941175, 17.64705882352941, 0.0029411764705882],
       [1.923076923076923, 0.0, 0.0],
       [2.092050209205021, 40.1673640167364, 0.002510460251046],
       [0.0, 12.40875912408759, 0.0007299270072992],
       [1.6666666666666663, 14.444444444444445, 0.0011111111111111],
       [0.0, 26.666666666666668, 0.0013333333333333],
       [0.9523809523809524, 23.80952380952381, 0.0009523809523809],
       [4.310344827586207, 14.655172413793103, 0.0017241379310344],
       [0.4098360655737705, 11.065573770491804, 0.0012295081967213],
       [2.2222222222222223, 22.22222222222222, 0.0011111111111111],
       [1.2048192771084338, 13.253012048192772, 0.0036144578313253],
       [0.0, 32.72727272727273, 0.0018181818181818],
       [1.1904761904761905, 9.523809523809524, 0.0023809523809523]],
      dtype=object)

In [70]:
# 넘파이 배열에서 결과(타겟) 데이터(평균 가격)로 사용할 데이터를 뽑아낸다. 
yData = numpy_array[:, 1]
# yData.reshape(-1, 1) # 위의 변화요인과 차원을 맞춰주어야 한다. 
# yData = data[:, 5:6] # 슬라이싱 이용
yData = numpy_array[:, [1]] # 인덱싱으로 뽑아낸 결과를 리스트화 시켜도 2차원 형태의 데이터로 뽑아낸다.
yData

array([[990.0],
       [922.0],
       [965.0],
       [755.0],
       [1016.0],
       [1115.0],
       [1213.0],
       [1169.0],
       [1222.0],
       [784.0],
       [791.0],
       [786.0],
       [1075.0],
       [1164.0],
       [1228.0],
       [1278.0],
       [1132.0],
       [942.0],
       [1438.0],
       [949.0],
       [1185.0],
       [989.0],
       [1232.0],
       [1321.0],
       [922.0],
       [1259.0],
       [562.0],
       [994.0],
       [1216.0],
       [1132.0],
       [1172.0],
       [1020.0],
       [785.0],
       [974.0],
       [914.0],
       [1147.0],
       [936.0],
       [790.0]], dtype=object)

In [71]:
# 뽑아낸 데이터를 텐서플로우에서 처리하기 위해서 placeholder를 만든다.
X = tf.placeholder(dtype=tf.float32, shape=[None, 3]) # 변화 요인을 기억할 placeholder
Y = tf.placeholder(dtype=tf.float32, shape=[None, 1]) # 결과 요인을 기억할 placeholder

In [72]:
# 다변인 선형 회귀 모델의 기울기(가중치)와 y 절편(바이어스)를 임의의 값으로 초기화한다. 
a = tf.Variable(tf.random_uniform([3, 1]), dtype=tf.float32) # 기울기, 내적을 하기 위해 4행 1열의 난수를 발생시킨다. 
b = tf.Variable(tf.random_uniform([1]), dtype=tf.float32) # y절편
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print('가중치\n', sess.run(a), sep='')
print('y절편\n', sess.run(b), sep='')

가중치
[[0.79810834]
 [0.98372436]
 [0.65063584]]
y절편
[0.71585083]

In [73]:
# 행렬의 곱셉(내적)을 이용해서 다변인 선형 회귀 모델의 가설로 사용할 식을 만든다 => 예측값을 계산하는 식
y = tf.matmul(X, a) + b # 예측값
# 오차(비용) 함수를 만든다. => 평균 제곱법 => 예측값(y)과 실제값(Y)의 편차에 제곱에 대한 평균
loss = tf.reduce_mean(tf.square(y - Y))
# 경사 하강법 알고리즘을 사용해서 오차 함수의 결과를 최소로 하는 기울기와 y절편을 찾는다. 
gradient_descent = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [74]:
# std = StandardScaler() # 표준화 스케일링 객체를 만든다. 
# # 표준화 스케일링을 적용할 데이터를 fit() 메소드로 먼저 학습(적합) 시킨 후 transform() 메소드를 실행한다. 
# y = df_label[['month_birth']]
# std.fit(y) # 표준화 스케일러에 month_birth 열을 적합시킨다. 
# print(y)
# # 적합(fit)된 표준화 스케일러를 기준으로 month_birth 열 데이터 값을 변형시킨다. 
# x_std = std.transform(y) # 적합(fit)된 표준화 스케일러를 기준으로 month_birth 열 데이터 값을 변형시킨다. 
# print(x_std)

In [76]:
# 학습 시킨다.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(100001):
    _, loss_, y_ = sess.run([gradient_descent, loss, y], feed_dict={X: xData, Y: yData})
    if epoch % 500 == 0:
        print('epoch: {:6d}, loss: {:12.3f}, price: {:8.2f}'.format(epoch, loss_, y_[0][0]))

epoch:      0, loss:  1107338.000, price:     4.10
epoch:    500, loss:   183312.984, price:   962.16
epoch:   1000, loss:   112111.156, price:   998.85
epoch:   1500, loss:    74781.398, price:  1014.60
epoch:   2000, loss:    54963.348, price:  1025.22
epoch:   2500, loss:    44440.414, price:  1032.89
epoch:   3000, loss:    38853.070, price:  1038.47
epoch:   3500, loss:    35886.254, price:  1042.54
epoch:   4000, loss:    34310.953, price:  1045.50
epoch:   4500, loss:    33474.523, price:  1047.66
epoch:   5000, loss:    33030.395, price:  1049.24
epoch:   5500, loss:    32794.570, price:  1050.38
epoch:   6000, loss:    32669.359, price:  1051.22
epoch:   6500, loss:    32602.869, price:  1051.83
epoch:   7000, loss:    32567.562, price:  1052.27
epoch:   7500, loss:    32548.822, price:  1052.60
epoch:   8000, loss:    32538.861, price:  1052.83
epoch:   8500, loss:    32533.572, price:  1053.00
epoch:   9000, loss:    32530.764, price:  1053.13
epoch:   9500, loss:    32529.270, price:  1053.22
epoch:  10000, loss:    32528.477, price:  1053.29
epoch:  10500, loss:    32528.053, price:  1053.33
epoch:  11000, loss:    32527.822, price:  1053.37
epoch:  11500, loss:    32527.703, price:  1053.40
epoch:  12000, loss:    32527.635, price:  1053.41
epoch:  12500, loss:    32527.600, price:  1053.43
epoch:  13000, loss:    32527.578, price:  1053.44
epoch:  13500, loss:    32527.562, price:  1053.44
epoch:  14000, loss:    32527.557, price:  1053.45
epoch:  14500, loss:    32527.547, price:  1053.45
epoch:  15000, loss:    32527.543, price:  1053.46
epoch:  15500, loss:    32527.539, price:  1053.46
epoch:  16000, loss:    32527.537, price:  1053.46
epoch:  16500, loss:    32527.533, price:  1053.46
epoch:  17000, loss:    32527.533, price:  1053.46
epoch:  17500, loss:    32527.523, price:  1053.46
epoch:  18000, loss:    32527.520, price:  1053.46
epoch:  18500, loss:    32527.520, price:  1053.46
epoch:  19000, loss:    32527.510, price:  1053.46
epoch:  19500, loss:    32527.514, price:  1053.46
epoch:  20000, loss:    32527.506, price:  1053.46
epoch:  20500, loss:    32527.500, price:  1053.46
epoch:  21000, loss:    32527.496, price:  1053.46
epoch:  21500, loss:    32527.490, price:  1053.46
epoch:  22000, loss:    32527.494, price:  1053.46
epoch:  22500, loss:    32527.484, price:  1053.46
epoch:  23000, loss:    32527.486, price:  1053.46
epoch:  23500, loss:    32527.480, price:  1053.46
epoch:  24000, loss:    32527.480, price:  1053.46
epoch:  24500, loss:    32527.475, price:  1053.46
epoch:  25000, loss:    32527.471, price:  1053.46
epoch:  25500, loss:    32527.463, price:  1053.46
epoch:  26000, loss:    32527.463, price:  1053.46
epoch:  26500, loss:    32527.457, price:  1053.46
epoch:  27000, loss:    32527.457, price:  1053.46
epoch:  27500, loss:    32527.453, price:  1053.46
epoch:  28000, loss:    32527.447, price:  1053.46
epoch:  28500, loss:    32527.443, price:  1053.46
epoch:  29000, loss:    32527.438, price:  1053.46
epoch:  29500, loss:    32527.438, price:  1053.46
epoch:  30000, loss:    32527.428, price:  1053.46
epoch:  30500, loss:    32527.432, price:  1053.46
epoch:  31000, loss:    32527.432, price:  1053.46
epoch:  31500, loss:    32527.422, price:  1053.46
epoch:  32000, loss:    32527.422, price:  1053.46
epoch:  32500, loss:    32527.414, price:  1053.46
epoch:  33000, loss:    32527.414, price:  1053.46
epoch:  33500, loss:    32527.412, price:  1053.46
epoch:  34000, loss:    32527.404, price:  1053.46
epoch:  34500, loss:    32527.400, price:  1053.46
epoch:  35000, loss:    32527.400, price:  1053.46
epoch:  35500, loss:    32527.395, price:  1053.46
epoch:  36000, loss:    32527.395, price:  1053.46
epoch:  36500, loss:    32527.385, price:  1053.46
epoch:  37000, loss:    32527.381, price:  1053.46
epoch:  37500, loss:    32527.381, price:  1053.46
epoch:  38000, loss:    32527.375, price:  1053.46
epoch:  38500, loss:    32527.375, price:  1053.46
epoch:  39000, loss:    32527.361, price:  1053.46
epoch:  39500, loss:    32527.361, price:  1053.46
epoch:  40000, loss:    32527.359, price:  1053.46
epoch:  40500, loss:    32527.359, price:  1053.46
epoch:  41000, loss:    32527.355, price:  1053.46
epoch:  41500, loss:    32527.352, price:  1053.46
epoch:  42000, loss:    32527.350, price:  1053.46
epoch:  42500, loss:    32527.346, price:  1053.46
epoch:  43000, loss:    32527.342, price:  1053.46
epoch:  43500, loss:    32527.338, price:  1053.46
epoch:  44000, loss:    32527.328, price:  1053.46
epoch:  44500, loss:    32527.332, price:  1053.46
epoch:  45000, loss:    32527.326, price:  1053.46
epoch:  45500, loss:    32527.326, price:  1053.46
epoch:  46000, loss:    32527.322, price:  1053.46
epoch:  46500, loss:    32527.316, price:  1053.46
epoch:  47000, loss:    32527.309, price:  1053.46
epoch:  47500, loss:    32527.307, price:  1053.46
epoch:  48000, loss:    32527.303, price:  1053.46
epoch:  48500, loss:    32527.303, price:  1053.46
epoch:  49000, loss:    32527.297, price:  1053.46
epoch:  49500, loss:    32527.293, price:  1053.46
epoch:  50000, loss:    32527.289, price:  1053.46
epoch:  50500, loss:    32527.289, price:  1053.46
epoch:  51000, loss:    32527.287, price:  1053.46
epoch:  51500, loss:    32527.279, price:  1053.46
epoch:  52000, loss:    32527.275, price:  1053.46
epoch:  52500, loss:    32527.273, price:  1053.46
epoch:  53000, loss:    32527.270, price:  1053.46
epoch:  53500, loss:    32527.270, price:  1053.46
epoch:  54000, loss:    32527.264, price:  1053.46
epoch:  54500, loss:    32527.256, price:  1053.46
epoch:  55000, loss:    32527.254, price:  1053.46
epoch:  55500, loss:    32527.250, price:  1053.46
epoch:  56000, loss:    32527.250, price:  1053.46
epoch:  56500, loss:    32527.246, price:  1053.46
epoch:  57000, loss:    32527.236, price:  1053.46
epoch:  57500, loss:    32527.234, price:  1053.46
epoch:  58000, loss:    32527.230, price:  1053.46
epoch:  58500, loss:    32527.227, price:  1053.46
epoch:  59000, loss:    32527.227, price:  1053.46
epoch:  59500, loss:    32527.221, price:  1053.46
epoch:  60000, loss:    32527.221, price:  1053.46
epoch:  60500, loss:    32527.217, price:  1053.46
epoch:  61000, loss:    32527.211, price:  1053.46
epoch:  61500, loss:    32527.211, price:  1053.46
epoch:  62000, loss:    32527.203, price:  1053.46
epoch:  62500, loss:    32527.201, price:  1053.46
epoch:  63000, loss:    32527.197, price:  1053.46
epoch:  63500, loss:    32527.191, price:  1053.46
epoch:  64000, loss:    32527.184, price:  1053.46
epoch:  64500, loss:    32527.184, price:  1053.46
epoch:  65000, loss:    32527.184, price:  1053.46
epoch:  65500, loss:    32527.178, price:  1053.46
epoch:  66000, loss:    32527.178, price:  1053.46
epoch:  66500, loss:    32527.174, price:  1053.46
epoch:  67000, loss:    32527.164, price:  1053.46
epoch:  67500, loss:    32527.168, price:  1053.46
epoch:  68000, loss:    32527.158, price:  1053.46
epoch:  68500, loss:    32527.158, price:  1053.46
epoch:  69000, loss:    32527.154, price:  1053.46
epoch:  69500, loss:    32527.150, price:  1053.46
epoch:  70000, loss:    32527.150, price:  1053.46
epoch:  70500, loss:    32527.145, price:  1053.46
epoch:  71000, loss:    32527.139, price:  1053.46
epoch:  71500, loss:    32527.139, price:  1053.46
epoch:  72000, loss:    32527.139, price:  1053.46
epoch:  72500, loss:    32527.125, price:  1053.46
epoch:  73000, loss:    32527.125, price:  1053.46
epoch:  73500, loss:    32527.121, price:  1053.46
epoch:  74000, loss:    32527.115, price:  1053.46
epoch:  74500, loss:    32527.115, price:  1053.46
epoch:  75000, loss:    32527.109, price:  1053.46
epoch:  75500, loss:    32527.109, price:  1053.46
epoch:  76000, loss:    32527.102, price:  1053.46
epoch:  76500, loss:    32527.102, price:  1053.46
epoch:  77000, loss:    32527.100, price:  1053.46
epoch:  77500, loss:    32527.092, price:  1053.46
epoch:  78000, loss:    32527.086, price:  1053.46
epoch:  78500, loss:    32527.082, price:  1053.46
epoch:  79000, loss:    32527.082, price:  1053.46
epoch:  79500, loss:    32527.076, price:  1053.46
epoch:  80000, loss:    32527.072, price:  1053.46

epoch:  80500, loss:    32527.076, price:  1053.46
epoch:  81000, loss:    32527.066, price:  1053.46
epoch:  81500, loss:    32527.062, price:  1053.46
epoch:  82000, loss:    32527.059, price:  1053.46
epoch:  82500, loss:    32527.057, price:  1053.46
epoch:  83000, loss:    32527.053, price:  1053.46
epoch:  83500, loss:    32527.053, price:  1053.46
epoch:  84000, loss:    32527.047, price:  1053.46
epoch:  84500, loss:    32527.043, price:  1053.46
epoch:  85000, loss:    32527.043, price:  1053.46
epoch:  85500, loss:    32527.039, price:  1053.46
epoch:  86000, loss:    32527.033, price:  1053.46
epoch:  86500, loss:    32527.029, price:  1053.46
epoch:  87000, loss:    32527.025, price:  1053.46
epoch:  87500, loss:    32527.023, price:  1053.46
epoch:  88000, loss:    32527.016, price:  1053.46
epoch:  88500, loss:    32527.010, price:  1053.46
epoch:  89000, loss:    32527.010, price:  1053.46
epoch:  89500, loss:    32527.010, price:  1053.46
epoch:  90000, loss:    32527.004, price:  1053.46
epoch:  90500, loss:    32526.996, price:  1053.46
epoch:  91000, loss:    32526.996, price:  1053.46
epoch:  91500, loss:    32526.990, price:  1053.46
epoch:  92000, loss:    32526.986, price:  1053.46
epoch:  92500, loss:    32526.984, price:  1053.46
epoch:  93000, loss:    32526.980, price:  1053.46
epoch:  93500, loss:    32526.980, price:  1053.46
epoch:  94000, loss:    32526.977, price:  1053.46
epoch:  94500, loss:    32526.967, price:  1053.46
epoch:  95000, loss:    32526.963, price:  1053.46
epoch:  95500, loss:    32526.961, price:  1053.46
epoch:  96000, loss:    32526.961, price:  1053.46
epoch:  96500, loss:    32526.953, price:  1053.46
epoch:  97000, loss:    32526.953, price:  1053.46
epoch:  97500, loss:    32526.947, price:  1053.46
epoch:  98000, loss:    32526.941, price:  1053.46
epoch:  98500, loss:    32526.941, price:  1053.46
epoch:  99000, loss:    32526.938, price:  1053.46
epoch:  99500, loss:    32526.934, price:  1053.46
epoch: 100000, loss:    32526.934, price:  1053.46

In [77]:
# 테스트
data = [[5, 10, 4]]
result = sess.run(y, feed_dict={X: data})
print(result)
print('1(㎢)당 고등 학교 개수가 :{:4.1f}개, 학원 개수가 : {:4.1f}개, 역 수가 : {:4.1f}일 때 '\
      '예상 집값은 면적(㎡)당 {:7,.2f}만원 입니다.'.format(data[0][0], data[0][1], data[0][2], result[0][0]))

[[1077.3322]]
1(㎢)당 고등 학교 개수가 : 5.0개, 학원 개수가 : 10.0개, 역 수가 :  4.0일 때 예상 집값은 면적(㎡)당 1,077.33만원 입니다.

In [36]:
from sklearn import datasets # 사이킷런이 제공하는 데이터셋을 사용하기 위해 import한다.
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split # 트레이닝 데이터와 테스트 데이터 나누기 위해
from sklearn.metrics import mean_squared_error # 평균 제곱 오차(MSE)를 계산하기 위해
from sklearn.metrics import mean_absolute_error # 평균 절대값 오차(MAE)를 계산하기 위해
from sklearn.metrics import r2_score # R 제곱값을 계산하귀 위해
from sklearn.metrics import silhouette_score # 실루엣 스코어를 계산하기 위해

In [37]:
numpy_array

array([['강북구', 990.0, 2.2304832713754648, ..., 0, 0, 0],
       ['강북구', 922.0, 0.0, ..., 0, 0, 0],
       ['강북구', 965.0, 0.4065040650406504, ..., 0, 0, 0],
       ...,
       ['중랑구', 1147.0, 1.2048192771084338, ..., 0, 0, 0],
       ['중랑구', 936.0, 0.0, ..., 0, 0, 0],
       ['중랑구', 790.0, 1.1904761904761905, ..., 0, 0, 0]], dtype=object)

In [39]:
X = numpy_array[:, 2:5]
y = numpy_array[:, [1]] 
X.shape

(38, 3)

In [40]:
# 트레이닝, 테스트 데이터 분할
from sklearn.model_selection import train_test_split # 트레이닝, 테스트 데이터 분할을 위해 import 한다.
X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state=1)
print(X_tn.shape, y_tn.shape, X_te.shape, y_te.shape) # 트레이닝 데이터와 테스트 데이터로 분할한다.

(28, 3) (28, 1) (10, 3) (10, 1)

In [41]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler # 데이터 표준화를 위해 import 한다.
std_scale = StandardScaler() # 표준화 스케일러 객체를 만든다.
# 표준화는 트레이닝 데이터를 기반으로 실행하므로 트레이닝 피쳐 데이터 X_tn을 표준화 스케일러에 적합시킨다.
X_tn_std = std_scale.fit_transform(X_tn) # 트레이닝 데이터를 적합 후 표준화 한다.
X_te_std = std_scale.transform(X_te) # 테스트 데이터를 표준화 한다.

In [42]:
from sklearn.neighbors import  KNeighborsClassifier

In [43]:
best_accuracy = 0 # 최고 정확도를 기억할 변수를 선언하고 0으로 초기화한다. 
# 1부터 10까지의 k값 후보 중에서 가장 높은 성능을 보이는 k값을 찾는다. 
for k in range(1, 11):
    clf_knn = KNeighborsClassifier(n_neighbors=k) # 최근접 이웃 모델을 만든다.
    clf_knn.fit(X_tn_std, y_tn) # 트레이닝 데이터로 학습한다. 
    knn_pred = clf_knn.predict(X_te_std) # 테스트 데이터로 예측한다. 
    # 테스트 데이터의 실제값과 테스트 데이터의 예측값으로 정확도를 계산한다. 
    accuracy = accuracy_score(y_te, knn_pred)
    print('k: {:2d}, accuary: {:6.3f}'.format(k, accuracy))
    # 가장 정확도가 높은 k를 계산한다.
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        final_k = k
# ===== for
print('=' * 80)
print('k: {:2d}, accuary: {:6.3f}'.format(final_k, best_accuracy))

ValueError: Unknown label type: 'unknown'

In [36]:
# 모델 생성 후 데이터 학습
from sklearn.linear_model import LinearRegression # 선형 회귀 알고리즘을 사용하기 위해 import 한다.
clf_lr = LinearRegression() # 선형 회귀 알고리즘 모델을 만든다.
# 표준화된 트레이닝 피쳐 데이터 X_tn_std와 트레이닝 타겟 데이터 y_tn를 모델에 넣어서 선형 회귀 알고리즘을 학습시킨다.
clf_lr.fit(X_tn_std, y_tn)

LinearRegression()

In [37]:
# 선형 회귀 분석 계수(가중치), 상수항(바이어스) 확인
print(clf_lr.coef_) # 가중치
print(clf_lr.intercept_) # 바이어스

[-0.1949987   0.00440079  0.61292906  0.36760412]
1.0357142857142858

In [38]:
# 모델 생성 후 데이터 학습
from sklearn.linear_model import Lasso # 라쏘 선형 회귀 알고리즘을 사용하기 위해 import 한다.
# 모델을 만들 때 alpha 옵션을 사용해서 제약 정도를 지정할 수 있다.
# alpha 옵션의 기본값은 1이고 반드시 양수로 지정해야 하며 값이 클수록 강한 제약식을 의미한다.
clf_lasso = Lasso(alpha=0.01) # 라쏘 선형 회귀 알고리즘 모델을 만든다.
# 표준화된 트레이닝 피쳐 데이터 X_tn_std와 트레이닝 타겟 데이터 y_tn를 모델에 넣어서 라쏘 선형 회귀 알고리즘을 학습시킨다.
clf_lasso.fit(X_tn_std, y_tn)

Lasso(alpha=0.01)

In [39]:
# 라소 선형 회귀 분석 계수, 상수항 확인
print(clf_lasso.coef_) # 가중치
print(clf_lasso.intercept_) # 바이어스

[-0.06246461 -0.0273801   0.39852084  0.44491366]
1.0357142857142863

In [40]:
# 모델 생성 후 데이터 학습
from sklearn.linear_model import Ridge # 릿지 선형 회귀 알고리즘을 사용하기 위해 import 한다.
# 릿지 선형 회귀 알고리즘은 라쏘 선형 회귀 알고리즘과 같이 alpha 옵션을 사용해서 제약 정도를 저정할 수 있다.
# alpha 옵션의 기본값은 1이고 반드시 양수로 지정해야 하며 값이 클수록 강한 제약식을 의미한다.
clf_ridge = Ridge(alpha=1) # 릿지 선형 회귀 알고리즘 모델을 만든다.
# 표준화된 트레이닝 피쳐 데이터 X_tn_std와 트레이닝 타겟 데이터 y_tn를 모델에 넣어서 라쏘 선형 회귀 알고리즘을 학습시킨다.
clf_ridge.fit(X_tn_std, y_tn)

Ridge(alpha=1)

모델 정확도 평가

피쳐간 연관관계 시각화